# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: booking slots

on:
  schedule:
    - cron: "50 7 * * *"
  workflow_dispatch:

jobs:
  buildFatJarForJVM:
    name: Build JVM jar application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Use Gradle packages cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build jar with Gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew shadowJar
      - run: |
          cp ./build/libs/venueBot-1.0-SNAPSHOT-all.jar ./venueBot-1.0-SNAPSHOT-all.jar
      - uses: actions/upload-artifact@v3
        with:
          name: jvmArtifacts-${{ github.sha }}
          path: |
            ./venueBot-1.0-SNAPSHOT-all.jar
            ./user.cfg
            ./times.json
          retention-days: 1

  runForAWhile:
    strategy:
      matrix:
        bucket: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 ]
    needs: buildFatJarForJVM
    name: Run for a while bucket ${{ matrix.bucket }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: jvmArtifacts-${{ github.sha }}
      - name: run for a while
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DURATION: "30"
          BUCKET: ${{ matrix.bucket }}
        run: |
          java -jar venueBot-1.0-SNAPSHOT-all.jar
